spring:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      lifecycle-management: start_and_stop
      stop-command: down

      skip:
        in-tests: true

logging:
  level:
    root: INFO
    org.zerock.puppyrun: DEBUG


# 날씨 보상 재시도 지연 TTL
weather:
  region-path: config/weather-regions.csv
  initialize-on-startup: true
  retry:
    api:
      ttl: 10m   # 10분 (ms)
    db:
      ttl: 10s    # 10초 (ms)
