spring:
  application:
    name=PuppyRun

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  docker:
    compose:
      lifecycle-management: start_and_stop
      skip:
        in-tests: false


discord:
  webhooks:
    url: ${discord_webhooks_url}
