spring:
  profiles:
    active: local # 기본적으로 local 실행 (배포 시 prod로 변경)

  application:
    name: PuppyRun

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        default_batch_fetch_size: 100

    show-sql: true

  docker:
    compose:
      lifecycle-management: start_and_stop
      skip:
        in-tests: false

  jackson:
    property-naming-strategy: SNAKE_CASE




discord:
  webhooks-url: ${discord_webhooks_url}

data-kr:
  api-key: ${DATA_API_KEY}
  forecest-url: ${DATA_FORECEST_URL}

firebase:
  account-path: ${FCM_ACCOUNT_PATH}
