services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: puppyrun-rabbitmq
    restart: "unless-stopped"

    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}


  backend:
    image: ${BACKEND_IMAGE}

    restart: "unless-stopped"

    ports:
      - "${BACKEND_PORT}:8080"
      - "127.0.0.1:8081:8081"

    volumes:
      - backend_data:/var/lib/backend

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}

    env_file:
      - /home/ubuntu/puppyrun/config/app.env

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"




volumes:
  backend_data:
